# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/bogdan/licenta/FPWAM/hardware/proj/User_Demo.cache/wt [current_project]
set_property parent.project_path /home/bogdan/licenta/FPWAM/hardware/proj/User_Demo.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths /home/bogdan/licenta/FPWAM/hardware/repo [current_project]
set_property ip_output_repo /home/bogdan/licenta/FPWAM/hardware/proj/User_Demo.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/bogdan/licenta/FPWAM/hardware/src/hdl/BinarySearch.vhd
  /home/bogdan/licenta/FPWAM/hardware/src/hdl/FpwamPkg.vhd
  /home/bogdan/licenta/FPWAM/hardware/src/hdl/BindUnit.vhd
  /home/bogdan/licenta/FPWAM/hardware/src/hdl/Memory.vhd
  /home/bogdan/licenta/FPWAM/hardware/src/hdl/ControlUnit.vhd
  /home/bogdan/licenta/FPWAM/hardware/src/hdl/DataFlowControl.vhd
  /home/bogdan/licenta/FPWAM/hardware/src/hdl/DerefUnit.vhd
  /home/bogdan/licenta/FPWAM/hardware/src/hdl/GPR.vhd
  /home/bogdan/licenta/FPWAM/hardware/src/hdl/uart.vhd
  /home/bogdan/licenta/FPWAM/hardware/src/hdl/UnifyUnit.vhd
  /home/bogdan/licenta/FPWAM/hardware/src/hdl/TrailUnit.vhd
  /home/bogdan/licenta/FPWAM/hardware/src/hdl/UnwindTrailUnit.vhd
  /home/bogdan/licenta/FPWAM/hardware/src/hdl/TopLevel.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/bogdan/licenta/FPWAM/hardware/src/constraints/Nexys4_Master.xdc
set_property used_in_implementation false [get_files /home/bogdan/licenta/FPWAM/hardware/src/constraints/Nexys4_Master.xdc]


synth_design -top TopLevel -part xc7a100tcsg324-1 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5


write_checkpoint -force -noxdef TopLevel.dcp

catch { report_utilization -file TopLevel_utilization_synth.rpt -pb TopLevel_utilization_synth.pb }
