
####################################################################################
# Generated by PlanAhead 14.7 built on 'Fri Sep 27 19:29:51 MDT 2013' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'Nexys4UserDemo.ucf'
####################################################################################

#Nexys4 User Demo User Constraint File
# System Clock, 100MHz
set_property PACKAGE_PIN E3 [get_ports clk]							
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
 

set_property PACKAGE_PIN C12 [get_ports {rst}]				
set_property IOSTANDARD LVCMOS33 [get_ports {rst}]
