
####################################################################################
# Generated by PlanAhead 14.7 built on 'Fri Sep 27 19:29:51 MDT 2013' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'Nexys4UserDemo.ucf'
####################################################################################

#Nexys4 User Demo User Constraint File
# System Clock, 100MHz
set_property PACKAGE_PIN E3 [get_ports clk_i]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'clk_i' has been applied to the port object 'clk_i'.
set_property IOSTANDARD LVCMOS33 [get_ports clk_i]

# PSRAM Memory Signals
set_property PACKAGE_PIN J18 [get_ports {Mem_A[0]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[0]' has been applied to the port object 'Mem_A[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[0]}]
set_property PACKAGE_PIN H17 [get_ports {Mem_A[1]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[1]' has been applied to the port object 'Mem_A[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[1]}]
set_property PACKAGE_PIN H15 [get_ports {Mem_A[2]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[2]' has been applied to the port object 'Mem_A[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[2]}]
set_property PACKAGE_PIN J17 [get_ports {Mem_A[3]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[3]' has been applied to the port object 'Mem_A[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[3]}]
set_property PACKAGE_PIN H16 [get_ports {Mem_A[4]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[4]' has been applied to the port object 'Mem_A[4]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[4]}]
set_property PACKAGE_PIN K15 [get_ports {Mem_A[5]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[5]' has been applied to the port object 'Mem_A[5]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[5]}]
set_property PACKAGE_PIN K13 [get_ports {Mem_A[6]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[6]' has been applied to the port object 'Mem_A[6]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[6]}]
set_property PACKAGE_PIN N15 [get_ports {Mem_A[7]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[7]' has been applied to the port object 'Mem_A[7]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[7]}]
set_property PACKAGE_PIN V16 [get_ports {Mem_A[8]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[8]' has been applied to the port object 'Mem_A[8]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[8]}]
set_property PACKAGE_PIN U14 [get_ports {Mem_A[9]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[9]' has been applied to the port object 'Mem_A[9]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[9]}]
set_property PACKAGE_PIN V14 [get_ports {Mem_A[10]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[10]' has been applied to the port object 'Mem_A[10]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[10]}]
set_property PACKAGE_PIN V12 [get_ports {Mem_A[11]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[11]' has been applied to the port object 'Mem_A[11]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[11]}]
set_property PACKAGE_PIN P14 [get_ports {Mem_A[12]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[12]' has been applied to the port object 'Mem_A[12]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[12]}]
set_property PACKAGE_PIN U16 [get_ports {Mem_A[13]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[13]' has been applied to the port object 'Mem_A[13]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[13]}]
set_property PACKAGE_PIN R15 [get_ports {Mem_A[14]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[14]' has been applied to the port object 'Mem_A[14]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[14]}]
set_property PACKAGE_PIN N14 [get_ports {Mem_A[15]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[15]' has been applied to the port object 'Mem_A[15]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[15]}]
set_property PACKAGE_PIN N16 [get_ports {Mem_A[16]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[16]' has been applied to the port object 'Mem_A[16]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[16]}]
set_property PACKAGE_PIN M13 [get_ports {Mem_A[17]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[17]' has been applied to the port object 'Mem_A[17]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[17]}]
set_property PACKAGE_PIN V17 [get_ports {Mem_A[18]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[18]' has been applied to the port object 'Mem_A[18]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[18]}]
set_property PACKAGE_PIN U17 [get_ports {Mem_A[19]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[19]' has been applied to the port object 'Mem_A[19]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[19]}]
set_property PACKAGE_PIN T10 [get_ports {Mem_A[20]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[20]' has been applied to the port object 'Mem_A[20]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[20]}]
set_property PACKAGE_PIN M16 [get_ports {Mem_A[21]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[21]' has been applied to the port object 'Mem_A[21]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[21]}]
set_property PACKAGE_PIN U13 [get_ports {Mem_A[22]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_A[22]' has been applied to the port object 'Mem_A[22]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_A[22]}]
set_property PACKAGE_PIN R11 [get_ports Mem_WEN]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_WEN' has been applied to the port object 'Mem_WEN'.
set_property IOSTANDARD LVCMOS33 [get_ports Mem_WEN]
set_property PACKAGE_PIN H14 [get_ports Mem_OEN]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_OEN' has been applied to the port object 'Mem_OEN'.
set_property IOSTANDARD LVCMOS33 [get_ports Mem_OEN]
set_property PACKAGE_PIN L18 [get_ports Mem_CEN]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_CEN' has been applied to the port object 'Mem_CEN'.
set_property IOSTANDARD LVCMOS33 [get_ports Mem_CEN]
set_property PACKAGE_PIN J13 [get_ports Mem_UB]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_UB' has been applied to the port object 'Mem_UB'.
set_property IOSTANDARD LVCMOS33 [get_ports Mem_UB]
set_property PACKAGE_PIN J15 [get_ports Mem_LB]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_LB' has been applied to the port object 'Mem_LB'.
set_property IOSTANDARD LVCMOS33 [get_ports Mem_LB]
set_property PACKAGE_PIN T15 [get_ports Mem_CLK]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_CLK' has been applied to the port object 'Mem_CLK'.
set_property IOSTANDARD LVCMOS33 [get_ports Mem_CLK]
set_property PACKAGE_PIN T13 [get_ports Mem_ADV]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_ADV' has been applied to the port object 'Mem_ADV'.
set_property IOSTANDARD LVCMOS33 [get_ports Mem_ADV]
set_property PACKAGE_PIN J14 [get_ports Mem_CRE]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_CRE' has been applied to the port object 'Mem_CRE'.
set_property IOSTANDARD LVCMOS33 [get_ports Mem_CRE]
set_property PACKAGE_PIN R12 [get_ports {Mem_DQ[0]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[0]' has been applied to the port object 'Mem_DQ[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[0]}]
set_property PACKAGE_PIN T11 [get_ports {Mem_DQ[1]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[1]' has been applied to the port object 'Mem_DQ[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[1]}]
set_property PACKAGE_PIN U12 [get_ports {Mem_DQ[2]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[2]' has been applied to the port object 'Mem_DQ[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[2]}]
set_property PACKAGE_PIN R13 [get_ports {Mem_DQ[3]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[3]' has been applied to the port object 'Mem_DQ[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[3]}]
set_property PACKAGE_PIN U18 [get_ports {Mem_DQ[4]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[4]' has been applied to the port object 'Mem_DQ[4]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[4]}]
set_property PACKAGE_PIN R17 [get_ports {Mem_DQ[5]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[5]' has been applied to the port object 'Mem_DQ[5]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[5]}]
set_property PACKAGE_PIN T18 [get_ports {Mem_DQ[6]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[6]' has been applied to the port object 'Mem_DQ[6]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[6]}]
set_property PACKAGE_PIN R18 [get_ports {Mem_DQ[7]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[7]' has been applied to the port object 'Mem_DQ[7]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[7]}]
set_property PACKAGE_PIN F18 [get_ports {Mem_DQ[8]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[8]' has been applied to the port object 'Mem_DQ[8]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[8]}]
set_property PACKAGE_PIN G18 [get_ports {Mem_DQ[9]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[9]' has been applied to the port object 'Mem_DQ[9]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[9]}]
set_property PACKAGE_PIN G17 [get_ports {Mem_DQ[10]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[10]' has been applied to the port object 'Mem_DQ[10]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[10]}]
set_property PACKAGE_PIN M18 [get_ports {Mem_DQ[11]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[11]' has been applied to the port object 'Mem_DQ[11]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[11]}]
set_property PACKAGE_PIN M17 [get_ports {Mem_DQ[12]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[12]' has been applied to the port object 'Mem_DQ[12]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[12]}]
set_property PACKAGE_PIN P18 [get_ports {Mem_DQ[13]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[13]' has been applied to the port object 'Mem_DQ[13]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[13]}]
set_property PACKAGE_PIN N17 [get_ports {Mem_DQ[14]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[14]' has been applied to the port object 'Mem_DQ[14]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[14]}]
set_property PACKAGE_PIN P17 [get_ports {Mem_DQ[15]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'Mem_DQ[15]' has been applied to the port object 'Mem_DQ[15]'.
set_property IOSTANDARD LVCMOS33 [get_ports {Mem_DQ[15]}]


# All timing constraint translations are rough conversions, intended to act as a template for further manual refinement. The translations should not be expected to produce semantically identical results to the original ucf. Each xdc timing constraint must be manually inspected and verified to ensure it captures the desired intent

create_clock -name clk_i -period 10.000 [get_ports clk_i]

# Ignore Clock Domain Crossing signals
# These signals are coming from the 100MHz clock domain
# ant are not time-critical: RGB LED, Temperature, Accelerometer
# and Mouse Controller data, going to the 108Mhz clock domain, the VGA display controller

# Define a new TNM for a FROM - TO constraint

get_false_path -from [all_fanout -endpoints_only -only_cells -flat -from [get_nets clk_i]] -to [all_fanout -endpoints_only -flat -from [get_nets Inst_VGA/pxl_clk]]
